# 科学技術計算 第3回レポートソースコード



In [ ]:
import numpy as np
from numpy.linalg import det, inv, matrix_rank, norm
from numpy import eye, identity, diag
rng = np.random.default_rng()

import scipy

from sklearn.datasets import load_iris

import sys
import psutil


import matplotlib.pyplot as plt
from matplotlib import rcParams
rcParams["savefig.bbox"] = "tight"
plt.gray()


<Figure size 640x480 with 0 Axes>

## 課題03-1


In [2]:
import matplotlib.pyplot as plt
from matplotlib import rcParams

#行列の積の計算する関数

def my_mm(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """行列積 ABを計算する関数

    引数:
        A (ndarray): m x n matrix
        B (ndarray): n x p matrix

    Returns:
        (ndarray): m x p matrix AB
    """
    #a,b が二次元行列であることを確認

    assert A.ndim == 2 and B.ndim == 2
    assert A.shape[1] == B.shape[0]

    #サイズを読み出し
    # print("A\n", A)
    #print("B\n", B)

    m, n = A.shape
    n, p  = B.shape

    C = np.zeros ((m, p))

    # 4*3 3*4の行列の積を計算
    for i in range (0, m):
        for j in range (0, p):
            for k in range (0, n):
                C[i][j] += A[i][k] * B[k][j]

    # print("C\n", C)

    return C
    

#以下は自作関数とライブラリの実行時間のプロットを作成するコード

for i in range(5):
    #行列のサイズ
    m = rng.integers(low=2, high=1000)
    n = rng.integers(low=2, high=1000)
    p = rng.integers(low=2, high=1000)
    A = rng.random(size=(m, n))
    B = rng.random(size=(n, p))

    print("A\n" ,A)
    print("B\n" ,B)

    #ライブラリの計算
    numpy_AB = A @ B

    #自作関数による計算
    my_AB = my_mm(A, B)
    print("my_AB\n" ,my_AB)

    assert np.allclose( #一致
        numpy_AB, my_AB
    ), "values doesn't match"

A
 [[0.70974492 0.79651253 0.84954348 ... 0.66854599 0.72500591 0.78944874]
 [0.25122687 0.64723943 0.0972914  ... 0.74355117 0.64713535 0.18485971]
 [0.04402379 0.66377313 0.90496276 ... 0.90931646 0.61013497 0.73291278]
 ...
 [0.4885968  0.77509604 0.57938034 ... 0.15688472 0.78496526 0.97638023]
 [0.69416792 0.79729174 0.78738776 ... 0.42972533 0.55685229 0.90223696]
 [0.42809744 0.11909929 0.03933435 ... 0.49868688 0.09877086 0.40503104]]
B
 [[0.83804628 0.44177747 0.81277235 ... 0.54226729 0.27328268 0.83025194]
 [0.17007421 0.76381704 0.28155452 ... 0.80159514 0.07905584 0.15211501]
 [0.33229212 0.03311804 0.64202386 ... 0.67368798 0.40483224 0.53516115]
 ...
 [0.65906175 0.45434139 0.24773743 ... 0.87422966 0.80044577 0.56448645]
 [0.53226811 0.22774403 0.7979622  ... 0.01226688 0.47532615 0.01150642]
 [0.1660749  0.77569787 0.23367419 ... 0.34051057 0.64755371 0.53026369]]
my_AB
 [[114.2765884  119.62820304 113.76999405 ... 118.76371431 111.07872293
  118.06790006]
 [113.611347

In [ ]:

for i in range(0,5):
    #行列のサイズ
    m = [2,5,10, 100,1000]
    n = [2,5,10, 100,1000]
    p = [2,5,10, 100,1000]
    A = rng.random(size=(m[i], n[i]))
    B = rng.random(size=(n[i], p[i]))

    #実行時間の計測
    print("CPU",m[i])
    %timeit numpy_inner_product = A @ B
    print("my",m[i])
    %timeit my_inner_product = my_mm(A, B)
    #計算し終わったから触らない！！

CPU 2
1.23 μs ± 30.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
my 2
6.11 μs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
CPU 5
1.24 μs ± 16 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
my 5
74.9 μs ± 1.93 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
CPU 10
1.3 μs ± 28.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
my 10
555 μs ± 14.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
CPU 100
60.9 μs ± 3.42 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
my 100
552 ms ± 10.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
CPU 1000
12.9 ms ± 108 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
my 1000
12min 16s ± 4min per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:

rcParams["savefig.bbox"] = "tight"
plt.gray()

n_list = [2, 5, 10, 100, 1000]

my_code_exec_times = [0.00000611, 0.0000749, 0.000555, 0.552, 736]  # dummy
numpy_exec_times = [0.00000123, 0.00000124, 0.0000013, 0.0000609, 0.0129]  # dummy

fig = plt.figure()
ax = fig.subplots()

ax.plot(n_list, my_code_exec_times, label="my code")
ax.plot(n_list, numpy_exec_times, label="numpy")

ax.set_title("Comparison of my_mv and numpy")
ax.set_xscale('log')
ax.set_yscale('log')
ax.set_xlabel('dimension $N$')
ax.set_ylabel('execution times [s]')
ax.legend()

plt.plot()
fig.savefig("compare_my_mv.pdf")


## 課題03-3

In [ ]:
# CSR形式の行列をもとの式に変換する関数の作成
def sparse_to_dense(A: scipy.sparse._csr.csr_array) -> np.ndarray:
    indptr = A.indptr
    indices = A.indices
    data = A.data

    answer = np.zeros((3,3))

    for i in range (0, len(indptr) - 1 ):
        for j in range (indptr[i],indptr[j + 1]):
            answer[i][indices[j]] = data[j]

    return answer


#やってみた
# 3x3密行列の例
dense_matrix = np.array(
    [[1, 0, 2],
     [0, 0, 3],
     [4, 5, 6]]
)


print("dense matrix A")
print(dense_matrix)
print()

# CSR形式に変換
A_csr = scipy.sparse.csr_array(dense_matrix)

#戻す
answer = sparse_to_dense(A_csr)
print (answer)

#確認してからランダム生成する


dense matrix A
[[1 0 2]
 [0 0 3]
 [4 5 6]]



UnboundLocalError: cannot access local variable 'j' where it is not associated with a value

## 課題03-4

In [ ]:
#単位ウ上三角行列, 上ヘッセンベルク行列
#単位上三角行列
def is_upper_triangular( A: np.ndarray, atol: float = 1e-8, rtol: float = 1e-8,) -> bool:
    return 0
#上ヘッセンベルク行列


#実行
n = 5
A = rng.random(size=(n, n))
print("A\n", A)

A_tri_upper = np.triu(A)
print("upper triangular matrix\n", A_tri_upper)

A_strict_tri_upper = np.triu(A, k=1)
print("strict upper traiangular matrix\n", A_strict_tri_upper)

A_upper_hessenberg = np.triu(A, k=-1)
print("upper Hessenbrerg matrix\n", A_upper_hessenberg)

s = np.triu(A, 0)
atrol
rtol
np.allclose()



## 課題03-5