# 科学技術計算 第3回レポートソースコード



In [1]:
import numpy as np
from numpy.linalg import det, inv, matrix_rank, norm
from numpy import eye, identity, diag
rng = np.random.default_rng()

import scipy

from sklearn.datasets import load_iris

import sys
import psutil


import matplotlib.pyplot as plt
from matplotlib import rcParams
rcParams["savefig.bbox"] = "tight"
plt.gray()


<Figure size 640x480 with 0 Axes>

## 課題03-1


In [2]:
import matplotlib.pyplot as plt
from matplotlib import rcParams

#行列の積の計算する関数

def my_mm(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """行列積 ABを計算する関数

    引数:
        A (ndarray): m x n matrix
        B (ndarray): n x p matrix

    Returns:
        (ndarray): m x p matrix AB
    """
    #a,b が二次元行列であることを確認

    assert A.ndim == 2 and B.ndim == 2
    assert A.shape[1] == B.shape[0]

    #サイズを読み出し
    # print("A\n", A)
    #print("B\n", B)

    m, n = A.shape
    n, p  = B.shape

    C = np.zeros ((m, p))

    # 4*3 3*4の行列の積を計算
    for i in range (0, m):
        for j in range (0, p):
            for k in range (0, n):
                C[i][j] += A[i][k] * B[k][j]

    # print("C\n", C)

    return C
    

#以下は自作関数とライブラリの実行時間のプロットを作成するコード

for i in range(5):
    #行列のサイズ
    m = rng.integers(low=2, high=1000)
    n = rng.integers(low=2, high=1000)
    p = rng.integers(low=2, high=1000)
    A = rng.random(size=(m, n))
    B = rng.random(size=(n, p))

    print("A\n" ,A)
    print("B\n" ,B)

    #ライブラリの計算
    numpy_AB = A @ B

    #自作関数による計算
    my_AB = my_mm(A, B)
    print("my_AB\n" ,my_AB)

    assert np.allclose( #一致
        numpy_AB, my_AB
    ), "values doesn't match"

A
 [[0.19768086 0.94798778 0.45152163 ... 0.80377876 0.12838691 0.11861077]
 [0.11793317 0.7664787  0.35353298 ... 0.38478147 0.03551502 0.23302031]
 [0.45741159 0.78888765 0.5756806  ... 0.15410181 0.23941831 0.77827089]
 ...
 [0.63745921 0.01672102 0.39218045 ... 0.49933284 0.71830351 0.94530795]
 [0.0576749  0.59730876 0.61765597 ... 0.97111552 0.63516746 0.93137432]
 [0.5612755  0.0082723  0.23296764 ... 0.85113575 0.89915386 0.30292251]]
B
 [[0.76001067 0.1457268  0.21651195 ... 0.11603656 0.54174902 0.43926475]
 [0.6778842  0.77588797 0.77037554 ... 0.85273159 0.77245062 0.63747507]
 [0.00133762 0.15314742 0.15497466 ... 0.08669652 0.19920739 0.54438175]
 ...
 [0.59333142 0.8005819  0.07617598 ... 0.99507632 0.47773492 0.61840975]
 [0.62002857 0.43830447 0.84556263 ... 0.18319567 0.57130809 0.687875  ]
 [0.91749651 0.36485499 0.49697772 ... 0.37797938 0.67852724 0.50343134]]
my_AB
 [[65.37754444 65.01863988 66.44408816 ... 73.21824903 63.60366467
  68.24365886]
 [63.40224574 63.8

In [5]:

for i in range(0,5):
    #行列のサイズ
    m = [2,5,10, 100,1000]
    n = [2,5,10, 100,1000]
    p = [2,5,10, 100,1000]
    A = rng.random(size=(m[i], n[i]))
    B = rng.random(size=(n[i], p[i]))

    #実行時間の計測
    print("CPU",m[i])
    %timeit numpy_inner_product = A @ B
    print("my",m[i])
    %timeit my_inner_product = my_mm(A, B)


CPU 2
1.24 µs ± 3.96 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
my 5
6.09 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
CPU 5


KeyboardInterrupt: 

In [ ]:

rcParams["savefig.bbox"] = "tight"
plt.gray()

n_list = [2, 5, 10, 100, 1000]

my_code_exec_times = [2, 100, 1000, 10000, 100000]  # dummy
numpy_exec_times = [1, 50, 200, 1000, 2000]  # dummy

fig = plt.figure()
ax = fig.subplots()

ax.plot(n_list, my_code_exec_times, label="my code")
ax.plot(n_list, numpy_exec_times, label="numpy")

ax.set_title("Comparison of my_mv and numpy")
ax.set_xscale('log')
ax.set_yscale('log')
ax.set_xlabel('dimension $N$')
ax.set_ylabel('execution times [s]')
ax.legend()

plt.plot()
fig.savefig("compare_my_mv.pdf")


## 課題03-3

In [ ]:

def sparse_to_dense(A: scipy.sparse._csr.csr_array) -> np.ndarray:


## 課題03-4

## 課題03-5